services:
  - type: web
    name: checkout-skala
    env: node
    buildCommand: npm install
    startCommand: node api/server.js
    envVars:
      - key: MP_ACCESS_TOKEN
        value: APP_USR-979073945795476-070311-4cd395c11c1ab047cd245ea48590fbea-3250900151
      - key: MP_PUBLIC_KEY
        value: APP_USR-a2fcf06f-d6a6-4ea0-8ea1-079cc2dfad20
